server:
  port: 8081

spring:
  application:
    name: Paperless API

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false